version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb+srv://kausiknelge:2nzBylEiTNgqkGtF@cluster0.o4f2iun.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./Backend:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ngrok tunnel service to expose local backend to internet
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"  # Ngrok web interface
    environment:
      - NGROK_AUTHTOKEN=31KnyAqV8wNrCnVeFvct7GbpIPz_44wApSKoxPCxVvgb7PtBt
    command: http backend:3000 --log=stdout
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - aarakshak-network

networks:
  aarakshak-network:
    driver: bridge 